# Generated by Django 3.0.6 on 2020-05-18 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200518_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='chapter',
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
            preserve_default=False,
        ),
    ]
