# Generated by Django 3.0.6 on 2020-05-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_lecture_src'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='video',
        ),
        migrations.AddField(
            model_name='lecture',
            name='ytvideo',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
