# Generated by Django 3.0.6 on 2020-05-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20200518_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='src',
            field=models.FileField(null=True, upload_to='course/videos'),
        ),
    ]
