# Generated by Django 3.0.6 on 2020-05-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20200519_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='src',
            field=models.FileField(default=None, upload_to='course/videos'),
            preserve_default=False,
        ),
    ]
