# Generated by Django 3.0.6 on 2020-05-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20200519_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='ytvideo',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
