# Generated by Django 3.0.6 on 2020-05-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20200519_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='src',
            field=models.FileField(default=None, upload_to='course/videos'),
        ),
    ]
