# Generated by Django 3.0.6 on 2020-05-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_auto_20200519_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='src',
            field=models.FileField(null=True, upload_to='course/videos'),
        ),
    ]
